name: ci

on: [pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ziishaned/jest-reporter-action@v0.0.1
      - name: Jest test coverage
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "yarn jest --coverage"
